In [1]:
import numpy as np

## Ques 1: Replace all odd numbers in arr with -1 #####

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2==1] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [2]:

## Ques 2: Convert a 1D array to a 2D array with 2 rows

arr = np.arange(10)

arr = arr.reshape((2,5))

arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
## Ques 3: How to generate custom sequence without hardcoding 

arr = np.array([1,2,3])

print (np.concatenate( [ np.tile(arr[0], 3) , np.tile(arr[1], 3), np.tile(arr[2], 3), np.tile(arr, 3) ] ))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [4]:
## Ques 4: How to get the common items between two numpy arrays

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

In [5]:
## Ques 5: How to get positions where elements of two arrays match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [6]:
## Ques 6: How to create a 2D array contaning random floats between 5 & 10

# Create a 2D array of shape 5x3 that contains random floats {5.0 - 10.0}

arr = np.random.uniform(5.0, 10.0, size=(5, 3))

arr

array([[8.27472507, 7.5303289 , 8.28505129],
       [9.54216711, 9.71988587, 7.87597359],
       [9.78537231, 6.40073164, 8.18594387],
       [6.1080164 , 9.89691336, 5.86907935],
       [9.01359231, 6.06360102, 8.45990083]])

In [7]:
## Ques 7: How to limit the number of item printed in output of numpy array to 6

a = np.arange(15)

np.set_printoptions(threshold = 6)

a

array([ 0,  1,  2, ..., 12, 13, 14])

In [8]:
## Ques 8: How to pretty print a numpy array by suppresing the scientific notation

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

np.set_printoptions(suppress=True)

print(rand_arr)

[[0.0005434  0.00027837 0.00042452]
 [0.00084478 0.00000472 0.00012157]
 [0.00067075 0.00082585 0.00013671]]


In [10]:
## Ques 9: How to swap 2 columns in 2D Array

arr = np.arange(9).reshape(3,3)

arr[:,[1, 2]] = arr[:,[2, 1]] #Swapping column 2 & 3
arr


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [11]:

## Ques 10: How to swap 2 ros in a 2D Array


arr = np.arange(9).reshape(3,3)

arr[[1, 2], :] = arr[[2, 1], :] #Swapping row 2 & 3
arr



array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])